server:
  port: 8083
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8048
  application:
    name: service-passenger-user
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/service-passenger-user?characterEncoding=utf-8&amp;serverTimezone=GMT%2B8
    username: root
    password: root



